//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class JCEEntities1 : DbContext
    {
        public JCEEntities1()
            : base("name=JCEEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cedula> cedula { get; set; }
        public virtual DbSet<Colegio> Colegio { get; set; }
        public virtual DbSet<municipio> municipio { get; set; }
        public virtual DbSet<nacionalidad> nacionalidad { get; set; }
        public virtual DbSet<ocupacion> ocupacion { get; set; }
        public virtual DbSet<provincia> provincia { get; set; }
        public virtual DbSet<recinto> recinto { get; set; }
        public virtual DbSet<sector> sector { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    
        public virtual ObjectResult<sp_get_cedulas_Result> sp_get_cedulas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_cedulas_Result>("sp_get_cedulas");
        }
    }
}
