//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class JCEEntities2 : DbContext
    {
        public JCEEntities2()
            : base("name=JCEEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cedula> cedulas { get; set; }
        public virtual DbSet<Colegio> Colegios { get; set; }
        public virtual DbSet<municipio> municipios { get; set; }
        public virtual DbSet<nacionalidad> nacionalidads { get; set; }
        public virtual DbSet<ocupacion> ocupacions { get; set; }
        public virtual DbSet<provincia> provincias { get; set; }
        public virtual DbSet<recinto> recintoes { get; set; }
        public virtual DbSet<sector> sectors { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<sp_get_cedulas_Result> sp_get_cedulas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_cedulas_Result>("sp_get_cedulas");
        }
    }
}
